# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

encode_utf8_one <- function(code_points) {
    .Call('_emojirx_encode_utf8_one', PACKAGE = 'emojirx', code_points)
}

encode_utf8 <- function(code_points) {
    .Call('_emojirx_encode_utf8', PACKAGE = 'emojirx', code_points)
}

